<?php

	define('WT_INTEGER', 1);
    define('WT_STRING', 2);
    define('WT_NUMERICAL', 3);

	$validator_list = array(
        'address' => properties(WT_STRING, 2, 255),
        'age_to' => properties(WT_INTEGER, 1, 200),
        'age_from' => properties(WT_INTEGER, 1, 200),
        'approved_1' => properties(WT_INTEGER, 1, 10),
        'approved_2' => properties(WT_STRING, 1, 10),
        'approved_3' => properties(WT_STRING, 1, 10),
        'approved_4' => properties(WT_STRING, 1, 10),
        'attending_physician' => properties(WT_STRING, 2, 255),
        'admission_date' => properties(WT_STRING, 2, 255),
        'admitted_by' => properties(WT_STRING, 2, 255),
        'attr_name' => properties(WT_STRING, 2, 255),
        'attr_value' => properties(WT_INTEGER, 2, 255),
        'attendance_date' => properties(WT_STRING, 1, 255),
        'application_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'admin_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'age' => properties(WT_INTEGER, 1, 100),
        'average_income' => properties(WT_NUMERICAL, 0, 'INFINITY'),
        'barangay' => properties(WT_STRING, 1, 255),
        'blood_pressure' => properties(WT_STRING, 1, 255),
        'business_name' => properties(WT_STRING, 1, 255),
        'brand' => properties(WT_STRING, 1, 255),
        'branch_id' => properties(WT_INTEGER, 1, 255),
        'bicep_circumference' => properties(WT_NUMERICAL, 1, 255),
        'birthdate' => properties(WT_STRING, 1, 255),
        'birth_place' => properties(WT_STRING, 1, 255),
        'civil_status' => properties(WT_INTEGER, 1, 255),
        'color_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'category_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'count' => properties(WT_INTEGER, 1, 'INFINITY'),
        'contact_number' => properties(WT_STRING, 11, 11, '/^09\d{9}$/', 'Input a valid contact number and atleast 11 characters'),
        'capillary_refill' => properties(WT_STRING, 0, 255),
        'cancel_reservation_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'color_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'course_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'course_year' => properties(WT_STRING, 2, 255),
        'change' => properties(WT_NUMERICAL, 0, 'INFINITY'),
        'customer_name' => properties(WT_STRING, 1, 255),
        'customer_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'city' => properties(WT_STRING, 1, 255),
        'chief_complaint' => properties(WT_STRING, 1, 255),
        'code' => properties(WT_STRING, 1, 255),
        'charge_bill_to' => properties(WT_STRING, 1, 255),
        'count_leave_month' => properties(WT_INTEGER, 1, 'INFINITY'),
        'count_leave_year' => properties(WT_INTEGER, 1, 'INFINITY'),
        'course_year_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'daily_rate' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'details' => properties(WT_STRING, 1, 255),
        'diagnosis' => properties(WT_STRING, 1, 255),
        'discharge_date' => properties(WT_STRING, 1, 255),
        'delivery_code' => properties(WT_STRING, 1, 255),
        'discount' => properties(WT_NUMERICAL, 0, 'INFINITY'),
        'department' => properties(WT_INTEGER, 1, 255),
        'department_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'description' => properties(WT_STRING, 1, 5000),
        'date_added' => properties(WT_STRING, 1, 255),
        'date_accepted' => properties(WT_STRING, 1, 255),
        'date_returned' => properties(WT_STRING, 1, 255),
        'date_renewal' => properties(WT_STRING, 1, 255),
        'date_received' => properties(WT_STRING, 1, 255),
        'date_created' => properties(WT_STRING, 1, 255),
        'date_sent' => properties(WT_STRING, 1, 255),
        'date_start' => properties(WT_STRING, 1, 255),
        'date_end' => properties(WT_STRING, 1, 255),
        'date_in' => properties(WT_STRING, 1, 255),
        'date_out' => properties(WT_STRING, 1, 255),
        'date_expired' => properties(WT_STRING, 1, 255),
        'date_consulted' => properties(WT_STRING, 1, 255),
        'date_arrived' => properties(WT_STRING, 2, 255),
        'date_order' => properties(WT_STRING, 2, 255),
        'date_of_birth' => properties(WT_STRING, 2, 255),
        'date_deliver' => properties(WT_STRING, 1, 255),
        'day_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'days' => properties(WT_STRING, 1, 255),
        'doctor_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'event_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'educational_attainment' => properties(WT_INTEGER, 1, 'INFINITY'),
        'end_date' => properties(WT_STRING, 1, 255),
        'enrollment_type' => properties(WT_INTEGER, 1, 100),
        'enrollment_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'enrollment_form_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'employee_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'employee_type' => properties(WT_INTEGER, 1, 'INFINITY'),
        'expected_course' => properties(WT_INTEGER, 1, 'INFINITY'),
        'encounter_problems' => properties(WT_STRING, 1, 255),
        'email' => properties(WT_STRING, 5, 255, '/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/', 'Please input a valid email address'),
        'email_address' => properties(WT_STRING, 5, 255, '/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,3})$/', 'Please input a valid email address'),
        'first_name' => properties(WT_STRING, 2, 255, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'full_name' => properties(WT_STRING, 2, 100, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'family_name' => properties(WT_STRING, 2, 255, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'family_id' => properties(WT_INTEGER, 0, 'INFINITY'),
        'file_location' => properties(WT_STRING, 2, 255),
        'folder_name' => properties(WT_STRING, 1, 255),
        'forearm_length' => properties(WT_NUMERICAL, 1, 255),
        'forearm_circumference' => properties(WT_NUMERICAL, 1, 255),
        'guardian_name' => properties(WT_STRING, 2, 255),
        'guardian_relationship' => properties(WT_STRING, 2, 255),
        'guardian_address' => properties(WT_STRING, 1, 255),
        'guardian_contact_number' => properties(WT_STRING, 1, 255),
        'guardian_occupation' => properties(WT_STRING, 1, 255),
        'guardian_average_income' => properties(WT_NUMERICAL, 0, 'INFINITY'),
        'gender' => properties(WT_INTEGER, 1, 2),
        'hand_length' => properties(WT_STRING, 1, 255),
        'hpi' => properties(WT_STRING, 1, 255),
        'heading' => properties(WT_STRING, 2, 3000),
        'home_address' => properties(WT_STRING, 2, 255),
        'insurance_fee' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'image_location' => properties(WT_STRING, 1, 255),
        'image1_location' => properties(WT_STRING, 1, 255),
        'image2_location' => properties(WT_STRING, 1, 255),
        'image3_location' => properties(WT_STRING, 1, 255),
        'image4_location' => properties(WT_STRING, 1, 255),
        'image5_location' => properties(WT_STRING, 1, 255),
        'image6_location' => properties(WT_STRING, 1, 255),
        'is_email_verified' => properties(WT_INTEGER, 1, 2),
        'is_included' => properties(WT_INTEGER, 1, 2),
        'is_paid' => properties(WT_INTEGER, 1, 10),
        'is_locked' => properties(WT_INTEGER, 1, 10),
        'is_accepted' => properties(WT_INTEGER, 1, 2),
        'id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'id_zero' => properties(WT_INTEGER, 0, 'INFINITY'),
        'is_archived' => properties(WT_INTEGER, 0, 10),
        'is_done' => properties(WT_INTEGER, 1, 2),
        'item_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'knees_to_foot' => properties(WT_NUMERICAL, 1, 255),
        'landline' => properties(WT_STRING, 2, 255),
        'leave_type_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'leave_name' => properties(WT_STRING, 1, 255),
        'last_name' => properties(WT_STRING, 2, 255, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'low_calf' => properties(WT_NUMERICAL, 1, 255),
        'option_id' => properties(WT_INTEGER, 0, 'INFINITY'),
        'major_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'max_students' => properties(WT_INTEGER, 1, 255),
        'max_calf' => properties(WT_NUMERICAL, 1, 255),
        'mid_calf' => properties(WT_NUMERICAL, 1, 255),
        'mobile_number' => properties(WT_STRING, 11, 11, '/^09\d{9}$/', 'Input a valid contact number and atleast 11 characters'),
        'medication_or_treatment' => properties(WT_STRING, 1, 255),
        'municipality' => properties(WT_STRING, 1, 255),
        'middle_name' => properties(WT_STRING, 2, 255, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'message' => properties(WT_STRING, 1, 5000),
        'message_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'name' => properties(WT_STRING, 1, 255, '/^[a-zA-Z., ]*$/', 'Only letters and some special characters like [space][.][,][-]'),
        'nationality' => properties(WT_STRING, 1, 255),
        'name_of_leave' => properties(WT_STRING, 1, 255),
        'number_of_days_leave' => properties(WT_INTEGER, 1, 255),
        'note' => properties(WT_STRING, 1, 3000),
        'no_of_passengers' => properties(WT_STRING, 1, 100),
        'note_1' => properties(WT_STRING, 1, 3000),
        'note_2' => properties(WT_STRING, 1, 3000),
        'note_3' => properties(WT_STRING, 1, 3000),
        'note_4' => properties(WT_STRING, 1, 3000),
        'number_of_leave' => properties(WT_INTEGER, 1, 255),
        'occupation' => properties(WT_STRING, 1, 255),
        'option_id' => properties(WT_NUMERICAL, 0, 'INFINITY'),
        'province' => properties(WT_STRING, 1, 255),
        'purchase_price' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'original_price' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'encounter_problems' => properties(WT_STRING, 1, 255),
        'payment_method' => properties(WT_INTEGER, 1, 2),
        'p_home_address' => properties(WT_STRING, 2, 255),
        'p_barangay' => properties(WT_STRING, 2, 255),
        'p_city' => properties(WT_STRING, 1, 255),
        'p_zip_code' => properties(WT_STRING, 1, 255),
        'plate_number' => properties(WT_STRING, 1, 255),
        'place_of_birth' => properties(WT_STRING, 1, 255),
        'pay_change' => properties(WT_NUMERICAL, -999999, 'INFINITY'),
        'person_type' => properties(WT_INTEGER, 1, 'INFINITY'),
        'person_type_answer' => properties(WT_STRING, 1, 255),
        'patient_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'product_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'proof_of_payment' => properties(WT_STRING, 1, 255),
        'position_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'pay' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'pulse_rate' => properties(WT_NUMERICAL , 1, 'INFINITY'),
        'password' => properties(WT_STRING, 1, 100),
        'past_grade_location' => properties(WT_STRING, 1, 255),
        /*'password' => properties(WT_STRING, 4, 255, '/^[a-zA-Z0-9]*$/', 'Only letters and numbers'),*/
        'price' => properties(WT_NUMERICAL, 1, 999999),
        'qualification' => properties(WT_STRING, 1, 3000),
        'quantity' => properties(WT_INTEGER, -999999, 'INFINITY'),
        'receiver_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'reason' => properties(WT_STRING, 1, 3000),
        'reason_for_decline' => properties(WT_STRING, 1, 1000),
        'relationship_to_patient' => properties(WT_STRING, 1, 255),
        'relationship_to_patient_contact_number' => properties(WT_STRING, 11, 11, '/^09\d{9}$/', 'Input a valid contact number and atleast 11 characters'),
        'religion' => properties(WT_INTEGER, 1, 255),
        'religion_id' => properties(WT_INTEGER, 1, 255),
        'resident_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'reservation_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'route' => properties(WT_INTEGER, 1, 'INFINITY'),
        'role_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'room' => properties(WT_STRING, 1, 255),
        'room_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'product_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        're_type_password' => properties(WT_STRING, 4, 255, '/^[a-zA-Z0-9]*$/', 'Only letters and numbers'),
        'respiratory_rates' => properties(WT_STRING, 1, 255),
        'selling_price' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'grand_total' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'search' => properties(WT_STRING, 1, 255),
        'date_acquired' => properties(WT_STRING, 1, 255),
        'date_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'date_registered' => properties(WT_STRING, 1, 255),
        'date_graduated' => properties(WT_STRING, 1, 255),
        'student_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'source' => properties(WT_STRING, 1, 255),
        'section' => properties(WT_STRING, 1, 255),
        'start_date' => properties(WT_STRING, 1, 255),
        'school_year' => properties(WT_STRING, 1, 255),
        'schedule_date' => properties(WT_STRING, 1, 255),
        'super_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'semester_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'semester_start' => properties(WT_STRING, 1, 255),
        'semester_end' => properties(WT_STRING, 1, 255),
        'semester_year_start' => properties(WT_STRING, 1, 255),
        'semester_year_end' => properties(WT_STRING, 1, 255),
        'sender_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'schedule_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'school_year_id' => properties(WT_INTEGER, 1, 2),
        'schedule_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'schedule_time' => properties(WT_STRING, 1, 255),
        'survey_form_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'supplier_name' => properties(WT_STRING, 1, 255),
        'suggestions' => properties(WT_STRING, 1, 255),
        'specialty' => properties(WT_INTEGER, 1, 'INFINITY'),
        'status' => properties(WT_INTEGER, 1, 'INFINITY'),
        'stocks' => properties(WT_INTEGER, 1, 'INFINITY'),
        'tin_number' => properties(WT_STRING, 15, 15, '/^\d{3}-\d{3}-\d{3}-\d{3}$/', 'Input a valid TIN Number e.g., (177-528-817-000)'),
        'title' => properties(WT_STRING, 1, 255),
        'time_in' => properties(WT_STRING, 1, 255),
        'time_out' => properties(WT_STRING, 1, 255),
        'time_start' => properties(WT_STRING, 1, 255),
        'time_end' => properties(WT_STRING, 1, 255),
        'target_date' => properties(WT_STRING, 1, 255),
        'target_time' => properties(WT_STRING, 1, 255),
        'transaction_code' => properties(WT_STRING, 1, 255),
        'texture_id' => properties(WT_INTEGER, 1, 255),
        'temperature' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'type' => properties(WT_INTEGER, 1, 999999),
        'type_of_leave' => properties(WT_INTEGER, 1, 255),
        'url' => properties(WT_STRING, 1, 500),
        'username' => properties(WT_STRING, 4, 50, '/^[a-zA-Z0-9]*$/', 'Only letters and numbers'),
        'total_payment_made_for_admission' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'total' => properties(WT_INTEGER, 1, 'INFINITY'),
        'top_calf' => properties(WT_NUMERICAL, 1, 255),
        'units' => properties(WT_INTEGER, 1, 'INFINITY'),
        'user_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'unit_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'unique_key' => properties(WT_STRING, 1, 500),
        'vacancies' => properties(WT_INTEGER, 1, 'INFINITY'),
        'ward_visited' => properties(WT_INTEGER, 1, 255),
        'weight' => properties(WT_NUMERICAL, 1, 'INFINITY'),
        'verification_code' => properties(WT_STRING, 1, 500),
        'year_level' => properties(WT_STRING, 1, 255),
        'year_level_id' => properties(WT_INTEGER, 1, 'INFINITY'),
        'years_of_experience' => properties(WT_INTEGER, 1, 'INFINITY'),
        'zip_code' => properties(WT_STRING, 1, 255, '/^[0-9]*$/', 'Only numbers'),
    );

    function not_required($key) {

        GLOBAL $validator_list;
        $validator_list[$key]['min'] = 0;
        
    }
    
    function properties($type, $min=0, $max=255, $regexp='none', $definition='none') {

        return array('type' => $type, 
                     'min' => $min,
                     'max' => $max,
                     'regexp' => $regexp,
                     'definition' => $definition
                    );

    }

    function custom_validator($key, $properties) {

        GLOBAL $validator_list;

        $validator_list[$key] = $properties;

    }


?>